### ISSUE TITLE
About the true class of the input data and the parameter range file

### ISSUE THREAD

**Issue by Alexplorer21** [PGB-LIV/FDRestimation#1]
If it's not too bothering, could you please specify the true class (whether the peptide is MS or is random) of the input data in a new file?
And is the parameter range file about the range of the random peptides pairs?
I'd be so appreciated if you can spare some time to answer these two questions!!

**Comment by Phorutai** [comment]
I do apologise for the extremely late reply

1. We used the know MS (Ture binding) or Random (False binding) peptides for training algorithm. The new input file should be unknown whether the peptides are true binding or false binding. MHCVision will estimate the false discovery rate and false probability, so, users can determine the threshold for determining true binding or false binding from those scores 
2. The parameter ranges are corresponding to MHC types. Those values were calculated from the distribution of random peptide predicted scores.

You can find more details in the full paper, https://academic.oup.com/bioinformatics/article/37/21/3830/6312548
